trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - .github
pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  
  - job: verification
    displayName: Templates Verification
    steps:
    
    - task: CmdLine@2
      displayName: Intall JSONlint
      inputs:
        script: 'sudo npm install jsonlint-cli -g'
    
    - task: CmdLine@2
      displayName: Lint ARM Templates
      inputs:
        script: 'jsonlint-cli **/*.json'
        workingDirectory: 'VM'
    
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Validate ARM Template
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure Internal'
        subscriptionId: $(SubscriptionID)
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'ARM_Examples'
        location: 'Southeast Asia'
        templateLocation: 'Linked artifact'
        csmFile: 'VM/template.json'
        csmParametersFile: 'VM/parameters.json'
        overrideParameters: '-adminPassword $(Password)'
        deploymentMode: 'Validation'
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Template as Artifact
      inputs:
        targetPath: 'VM'
        artifact: 'VMTemplate'
        publishLocation: 'pipeline'

- stage: CD
  displayName: Deployments
  condition: ne(variables['Build.Reason'], 'PullRequest')
  jobs:
  
  - deployment: prod    
    displayName: Deploy to Prod
    environment: Production
    strategy:
      runOnce:
         deploy:
           steps:

             - task: DownloadPipelineArtifact@2
               inputs:
                 buildType: 'current'
                 artifactName: 'VMTemplate'
                 targetPath: '$(Pipeline.Workspace)'

             - task: AzureResourceManagerTemplateDeployment@3
               displayName: Deploy ARM Template
               inputs:
                 deploymentScope: 'Resource Group'
                 azureResourceManagerConnection: 'Azure Internal'
                 subscriptionId: $(SubscriptionID)
                 action: 'Create Or Update Resource Group'
                 resourceGroupName: 'ARM_Examples'
                 location: 'Southeast Asia'
                 templateLocation: 'Linked artifact'
                 csmFile: 'VMTemplate/template.json'
                 csmParametersFile: 'VMTemplate/parameters.json'
                 overrideParameters: '-adminPassword $(Password)'
                 deploymentMode: Incremental