trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  
  - job: verification
    displayName: Templates Verification
    steps:
    - task: AzSKARMTemplateChecker@4
      displayName: ARM Template Checker 
      inputs:
        ARMTemplateFilePath: '.'

