trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - .github
pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  
  - job: verification
    displayName: Templates Verification
    steps:
    
    - task: CmdLine@2
      displayName: Intall JSONlint
      inputs:
        script: 'sudo npm install jsonlint-cli -g'
    
    - task: CmdLine@2
      displayName: Lint ARM Templates
      inputs:
        script: 'jsonlint-cli **/*.json'
        workingDirectory: 'VM'
    
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Validate ARM Template
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Microsoft Azure Internal Consumption(cd558c1c-643a-409c-a1f0-d4f07aafadc9)'
        subscriptionId: 'cd558c1c-643a-409c-a1f0-d4f07aafadc9'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'ARM_Examples'
        location: 'Southeast Asia'
        templateLocation: 'Linked artifact'
        csmFile: 'VM/template.json'
        deploymentMode: 'Validation'
    

