trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - .github
  pr:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  
  - job: verification
    displayName: Templates Verification
    steps:
    
    - task: CmdLine@2
      displayName: Intall JSONlint
      inputs:
        script: 'npm install jsonlint-cli -g'
        workingDirectory: 'VM'
    
    - task: CmdLine@2
      displayName: Lint ARM Templates
      inputs:
        script: 'jsonlint-cli **/*.json'
        workingDirectory: 'VM'
    

