trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  
  - job: verification
    displayName: Templates Verification
    steps:
    
    - task: Npm@1
      displayName: Intall JSONlint
      inputs:
        command: 'custom'
        customCommand: 'install jsonlint -g'
    
    - task: CmdLine@2
      displayName: Lint ARM Templates
      inputs:
        script: 'jsonlint *.json'
        workingDirectory: 'VM'
    

