name: Virtual Machine CICD

on:
  push:
    branches: [ main ]
    paths-ignore: azure-pipelines-*.*
  pull_request:
    branches: [ main ]    
    paths-ignore: azure-pipelines-*.*

  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: ARM Template Toolkit (ARM TTK)
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: VM/template.json
      
