name: Virtual Machine CICD

on:
  push:
    branches: [ main ]
    paths-ignore: azure-pipelines-*.*
  pull_request:
    branches: [ main ]    
    paths-ignore: azure-pipelines-*.*

  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: ARM Template Toolkit (ARM TTK) Validaiton    
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: VM/template.json
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Validate ARM Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          region: southeastasia
          resourceGroupName: ARM_Examples
          template: VM/template.json
          deploymentMode: Validate
          parameters: VM/parameters.json adminPassword=xxx
            
